parameters:
- name: userName
  displayName: 'User Name'
  type: string
  default: 'Joshua'

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- template: learning/templates/stage.yml
  parameters:
    userName: ${{ parameters.userName }}