trigger: 
  -main


pool: 
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/print.yml
    parameters:
      message: 'World'
  - template: templates/build-info.yml
  - template: templates/file-explorer.yml
  - template: templates/Greeting.yml
    parameters:
      name: 'Joshua'