parameters:
  - name: name
    type: string
  - name: message
    type: string


jobs:
  - job: PrintGreeting
    displayName: 'DoAllJob'
    steps: |
    - template: templates/Greeting.yml
      parameters:
        name: ${{ parameters.name }}
    - template: templates/print.yml
      parameters:
        message: ${{ parameters.message }}
    - template: templates/file-explorer.yml
    - template: templates/build-info.yml
