parameters:
  - name: userName
    type: string

stages:

- stage: GreetingStage

  jobs:
  - job: GreetingJob

    steps:
    - template: Greeting.yml
      parameters:
        name: ${{ parameters.userName }}

- stage: BuildInfoStage

  dependsOn: GreetingStage

  jobs:
  - job: BuildInfoJob

    steps:
    - template: build-info.yml

- stage: ExplorerStage

  dependsOn: BuildInfoStage

  condition: false

  jobs:
  - job: ExplorerJob

    steps:
    - template: file-explorer.yml