parameters:
- name: userName
  type: string

- name: environment
  type: string

stages:

- stage: GreetingStage


  condition:  or(eq(${{ parameters.environment }}, 'dev'), eq(${{ parameters.environment }}, 'prod'))
  jobs:
  - job: GreetingJob
  

    steps:
    - template: Greeting.yml
      parameters:
        name: ${{ parameters.userName }}

- stage: BuildInfoStage

  dependsOn: GreetingStage

  condition:  or(eq(${{ parameters.environment }}, 'dev'), eq(${{ parameters.environment }}, 'prod'))

  jobs:
  - job: BuildInfoJob

    steps:
    - template: build-info.yml

- stage: ExplorerStage

  dependsOn: BuildInfoStage

  condition: eq(${{ parameters.environment }}, 'prod')

  jobs:
  - job: ExplorerJob

    steps:
    - template: file-explorer.yml