stages:

- stage: GreetingStage
  displayName: "Greeting Stage"

  jobs:
  - template: job.yml
    parameters:
      runGreeting: true

- stage: InformationStage
  displayName: "Information Stage"

  jobs:
  - template: job.yml
    parameters:
      runBuildInfo: true

- stage: ExplorerStage
  displayName: "Explorer Stage"

  jobs:
  - template: job.yml
    parameters:
      runExplorer: true